// Code generated by goctl. DO NOT EDIT.
package common

import (
	"go-admin-template/handler/common"

	"github.com/gin-gonic/gin"
)

func RegisterCommonRoute(e *gin.Engine) {
	g := e.Group("")
	g.POST("/upload/image", common.UploadImageHandle)
}
