// Code generated by goctl. DO NOT EDIT.
package role

import (
	"go-admin-template/handler/admin/role"

	"github.com/gin-gonic/gin"
)

func RegisterAdminRoleRoute(e *gin.Engine) {
	g := e.Group("")
	g.GET("/admin/role", role.ListHandle)
	g.GET("/admin/role/:id", role.DetailHandle)
	g.POST("/admin/role", role.AddHandle)
	g.PUT("/admin/role/:id", role.EditHandle)
	g.DELETE("/admin/role/:id", role.DelHandle)
}
